// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupSystemHosts() {
  return window['go']['main']['App']['BackupSystemHosts']();
}

export function CreateHostGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateHostGroup'](arg1, arg2);
}

export function DeleteHostGroup(arg1) {
  return window['go']['main']['App']['DeleteHostGroup'](arg1);
}

export function GetAllHostGroups() {
  return window['go']['main']['App']['GetAllHostGroups']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDataLocation() {
  return window['go']['main']['App']['GetDataLocation']();
}

export function GetSystemHosts() {
  return window['go']['main']['App']['GetSystemHosts']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetDataLocation(arg1) {
  return window['go']['main']['App']['SetDataLocation'](arg1);
}

export function ToggleHostGroup(arg1) {
  return window['go']['main']['App']['ToggleHostGroup'](arg1);
}

export function UpdateHostGroup(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateHostGroup'](arg1, arg2, arg3, arg4);
}

export function UpdateHostsMode(arg1) {
  return window['go']['main']['App']['UpdateHostsMode'](arg1);
}

export function UpdateSystemHosts() {
  return window['go']['main']['App']['UpdateSystemHosts']();
}
