// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function BackupSystemHosts():Promise<void>;

export function CreateHostGroup(arg1:string,arg2:string):Promise<models.HostGroup>;

export function DeleteHostGroup(arg1:string):Promise<void>;

export function GetAllHostGroups():Promise<Array<models.HostGroup>>;

export function GetConfig():Promise<models.SystemConfig>;

export function GetDataLocation():Promise<string>;

export function GetSystemHosts():Promise<models.HostsFile>;

export function OpenDirectoryDialog():Promise<string>;

export function SaveConfig(arg1:models.SystemConfig):Promise<void>;

export function SetDataLocation(arg1:string):Promise<void>;

export function ToggleHostGroup(arg1:string):Promise<void>;

export function UpdateHostGroup(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function UpdateHostsMode(arg1:string):Promise<void>;

export function UpdateSystemHosts():Promise<void>;
